/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*;

/**
 *
 * @author ASUS1
 */
public class Interfaz extends javax.swing.JFrame {

    public static Connection miConexion;  
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInsertarTienda = new javax.swing.JLabel();
        jLabelCodigoTienda = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldCodigoTienda = new javax.swing.JTextField();
        jLabelNombreTienda = new javax.swing.JLabel();
        jTextFieldAdministrador = new javax.swing.JTextField();
        jLabelCodigoAdmin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jLabelDescripcion = new javax.swing.JLabel();
        jButtonInsertarTienda = new javax.swing.JButton();
        jTextFieldAdressId = new javax.swing.JTextField();
        jLabelAdressId = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelInsertarTienda.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabelInsertarTienda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInsertarTienda.setText("   Insertar Tienda");
        getContentPane().add(jLabelInsertarTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 310, 30));

        jLabelCodigoTienda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCodigoTienda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodigoTienda.setText("Codigo");
        getContentPane().add(jLabelCodigoTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        jTextFieldNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 170, -1));

        jTextFieldCodigoTienda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCodigoTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoTiendaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCodigoTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 170, -1));

        jLabelNombreTienda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNombreTienda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreTienda.setText("Nombre");
        getContentPane().add(jLabelNombreTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jTextFieldAdministrador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAdministradorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 170, -1));

        jLabelCodigoAdmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCodigoAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodigoAdmin.setText("Codigo de administrador");
        getContentPane().add(jLabelCodigoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 150, 20));

        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));

        jLabelDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescripcion.setText("Descripción");
        getContentPane().add(jLabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        jButtonInsertarTienda.setText("INSERTAR");
        jButtonInsertarTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarTiendaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInsertarTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 100, 30));
        getContentPane().add(jTextFieldAdressId, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 170, -1));

        jLabelAdressId.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdressId.setText("Direccion");
        getContentPane().add(jLabelAdressId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Holitas.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodigoTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoTiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoTiendaActionPerformed

    private void jTextFieldAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdministradorActionPerformed

    private void jButtonInsertarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarTiendaActionPerformed
        int Codigo = Integer.parseInt(jTextFieldCodigoTienda.getText());
        String Nombre = jTextFieldNombre.getText();
        int ManagerId = Integer.parseInt(jTextFieldAdministrador.getText());
        int direccion = Integer.parseInt(jTextFieldAdressId.getText());
        String descripcion = jTextAreaDescripcion.getText();
        Consultas.agregarTienda(miConexion, Codigo, Nombre, ManagerId, direccion, descripcion);
    }//GEN-LAST:event_jButtonInsertarTiendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        miConexion = Consultas.conectar();
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInsertarTienda;
    private javax.swing.JLabel jLabelAdressId;
    private javax.swing.JLabel jLabelCodigoAdmin;
    private javax.swing.JLabel jLabelCodigoTienda;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelInsertarTienda;
    private javax.swing.JLabel jLabelNombreTienda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextField jTextFieldAdministrador;
    private javax.swing.JTextField jTextFieldAdressId;
    private javax.swing.JTextField jTextFieldCodigoTienda;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
